CREATE TABLE connexion (
    id_connexion INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    telephone INT UNSIGNED NOT NULL,
    email VARCHAR(100) NOT NULL,
    pseudo VARCHAR(50) NOT NULL,
    mdp VARCHAR(50) NOT NULL,
    CONSTRAINT PK_CONNEXTION PRIMARY KEY(id_connexion))
    ENGINE = INNODB CHARACTER SET utf8;
